import sys
sys.path.insert(0, ".")
from rag.vector_store import get_vector_store

GUIDES = [
    # ===== MANALI =====
    {"id": "manali_overview", "text": "Manali is a high-altitude Himalayan resort in Himachal Pradesh at 2050m. Best visited May-June and Oct-Nov. Key attractions: Rohtang Pass (snow, 51km), Solang Valley (adventure sports), Old Manali (cafes, backpacker vibe), Hadimba Temple (free), Vashisht Hot Springs (free). Nearest airport: Bhuntar (50km). Buses from Delhi: ₹700-1200 Volvo overnight.", "metadata": {"destination": "Manali", "source": "travel_guide", "type": "overview"}},
    {"id": "manali_adventure", "text": "Adventure in Manali: Beas Kund trek (3 days, moderate, ₹2500 with guide), Hampta Pass trek (4 days, difficult, ₹6000-8000 with agency), Chandrakhani Pass (3 days, ₹3000). River rafting on Beas (Grade 2-3, ₹600-800 for 14km). Rock climbing at Solang Valley. Paragliding ₹600-800. Zorbing ₹400. Skiing Jan-March at Solang. Mountain biking rentals ₹300/day. Best season May-September.", "metadata": {"destination": "Manali", "source": "travel_guide", "type": "adventure"}},
    {"id": "manali_budget", "text": "Manali 5-day budget breakdown: Bus Delhi-Manali-Delhi ₹1400-2400. Local taxi/shared cab ₹1500-2500 total. Zostel dorm 5 nights ₹2500-4000, budget guesthouse ₹3000-6000. Food 5 days at dhabas ₹2000-3500. Rohtang permit ₹550. Activities (rafting+paragliding+1 trek) ₹3000-5000. Total possible under ₹15,000-20,000.", "metadata": {"destination": "Manali", "source": "budget_guide", "type": "budget"}},
    {"id": "manali_food", "text": "Best food in Manali: Drifters Cafe Old Manali (breakfast ₹150, great coffee), Chopstick Restaurant (momos ₹80, noodles ₹120), Johnson Cafe (trout fish ₹350, must try), Cafe 1947 (wood-fired pizza ₹200), Lazy Dog (rooftop views, pasta ₹180), Il Forno (Italian, ₹200-300). Local dhabas: dal rice ₹80, rajma chawal ₹90.", "metadata": {"destination": "Manali", "source": "food_guide", "type": "food"}},
    {"id": "manali_hotels", "text": "Accommodation in Manali: Budget - Zostel (dorm ₹500, private ₹1200), Banjara Camps (dorm ₹400), Old Manali guesthouses ₹600-900. Mid-range - Hotel Snowflake ₹1500-2000, Apple Country Resort ₹2000-2500. Luxury - Span Resort ₹8000+, Solang Valley Resort ₹5000+. Book 2 months ahead for May-June peak season.", "metadata": {"destination": "Manali", "source": "hotel_guide", "type": "accommodation"}},
    {"id": "manali_hidden", "text": "Hidden gems in Manali: Naggar Castle (15km away, ₹50 entry, Nicholas Roerich Art Gallery nearby, stunning valley views, fewer tourists), Jana Waterfall (7km from Manali, free entry, beautiful and less crowded), Hamta village (authentic Himachali culture, 8km), Arjun Gufa cave (Old Manali, free, peaceful), Chandratal Lake (4300m altitude, stunning blue lake, overnight camping allowed).", "metadata": {"destination": "Manali", "source": "hidden_gems", "type": "hidden_gems"}},
    {"id": "manali_safety", "text": "Manali safety tips: Altitude sickness possible above 3000m - acclimatize first day, drink water, avoid alcohol. Rohtang Pass requires Inner Line Permit (₹550, online booking). Roads can close in heavy snow. Carry warm clothes even in summer. Mobile network weak in remote areas - download offline maps. BSNL works best in remote Himachal. Emergency: Tourist Police 01902-252342.", "metadata": {"destination": "Manali", "source": "safety_guide", "type": "safety"}},

    # ===== GOA =====
    {"id": "goa_overview", "text": "Goa is India's smallest state and top beach destination. North Goa: Calangute, Baga, Anjuna, Vagator (parties, water sports, nightlife, flea markets). South Goa: Palolem, Agonda, Colva (peaceful, cleaner, family-friendly). Best season November-February. Rainy season June-September (cheap but monsoon). Airport: Dabolim (domestic) and Mopa (new international).", "metadata": {"destination": "Goa", "source": "travel_guide", "type": "overview"}},
    {"id": "goa_budget", "text": "Goa 5-day budget: Flight from Hyderabad ₹3000-6000 return. Scooter rental ₹300-400/day (best transport). Budget guesthouse ₹800-1500/night, beach hut ₹1000-2000, mid-range hotel ₹2500-4000. Food: shack meals ₹200-400, restaurant ₹400-700. Water sports package ₹1500-2500. Beer at shack ₹80-120. Total 5 days: ₹15,000-25,000 including flights.", "metadata": {"destination": "Goa", "source": "budget_guide", "type": "budget"}},
    {"id": "goa_beaches", "text": "Goa beaches guide: Palolem (crescent shaped, calm water, best for swimming, South Goa), Agonda (peaceful, turtles nesting, no loud music), Anjuna (rocky, famous flea market Wednesday, good for watching sunsets), Vagator (dramatic red cliffs, two beaches), Calangute (crowded but water sports hub), Arambol (backpacker favorite, drum circles, North Goa), Butterfly Beach (accessible only by boat, secluded, ₹300 boat ride).", "metadata": {"destination": "Goa", "source": "beach_guide", "type": "beaches"}},
    {"id": "goa_food", "text": "Must-eat in Goa: Fish curry rice (local staple, ₹120-200), Prawn Balchao (spicy pickle prawns), Bebinca (layered dessert), Chicken Xacuti (coconut curry), Goan sausage (chourico). Best restaurants: Fisherman's Wharf (Cavelossim, seafood, ₹400-800), Gunpowder (Assagao, ₹300-500), Vinayak (local Goan thali ₹150). Beach shacks: Martin's Corner, Brittos.", "metadata": {"destination": "Goa", "source": "food_guide", "type": "food"}},
    {"id": "goa_hidden", "text": "Hidden gems in Goa: Divar Island (ferry from Old Goa, Portuguese heritage, cycling, very few tourists), Chorao Island (bird sanctuary, mangroves, crocodiles), Cabo de Rama Fort (South Goa, dramatic cliff views, free entry), Dudhsagar Falls (4-tiered 310m waterfall, best June-October, jeep safari from Mollem ₹2500), Fontainhas Latin Quarter (Old Goa, Portuguese tiled houses, cafe culture).", "metadata": {"destination": "Goa", "source": "hidden_gems", "type": "hidden_gems"}},
    {"id": "goa_nightlife", "text": "Goa nightlife: Curlies Beach Shack Anjuna (legendary sunset parties), Tito's Club Baga (₹500-1000 entry), Club Cubana Arpora (Saturday Night Bazaar nearby), Silent Noise Club Palolem (headphone party on beach, ₹300), Leopard Valley (Anjuna, outdoor parties), Nine Bar Vagator (sunset techno). Anjuna Flea Market every Wednesday. Ingo's Saturday Night Bazaar (Arpora, shopping+food+live music, free entry).", "metadata": {"destination": "Goa", "source": "nightlife_guide", "type": "nightlife"}},

    # ===== KERALA =====
    {"id": "kerala_overview", "text": "Kerala is India's most scenic state known as God's Own Country. Top experiences: Alleppey backwaters (houseboat stays), Munnar tea plantations, Wayanad wildlife, Kovalam and Varkala beaches, Thekkady wildlife sanctuary, Kochi heritage city. Best season October-March. Ayurvedic treatments widely available. Nearest airports: Kochi, Trivandrum, Kozhikode.", "metadata": {"destination": "Kerala", "source": "travel_guide", "type": "overview"}},
    {"id": "kerala_budget", "text": "Kerala 7-day budget: Flight to Kochi from Hyderabad ₹4000-8000 return. Houseboat Alleppey 1 night (2 person) ₹6000-12000. Budget homestay ₹800-1500/night. Mid-range hotel ₹2000-3500. Food: Kerala meals (sadya) ₹150-200, restaurant ₹300-500. KSRTC bus travel cheap ₹100-300 between cities. Total 7 days: ₹20,000-35,000 including flights.", "metadata": {"destination": "Kerala", "source": "budget_guide", "type": "budget"}},
    {"id": "kerala_backwaters", "text": "Kerala backwaters: Alleppey (Alappuzha) is the houseboat capital. Day cruise from ₹1500/person, overnight houseboat from ₹6000 (2 persons, includes meals). Shikara boat rides ₹300-500/hour. Kumarakom Bird Sanctuary nearby. Kollam to Alleppey ferry (8 hours, ₹400, most scenic). Punnamada Lake, Vembanad Lake. Best experienced October-March. Book houseboats in advance during peak season.", "metadata": {"destination": "Kerala", "source": "backwaters_guide", "type": "backwaters"}},
    {"id": "kerala_food", "text": "Kerala food must-try: Kerala fish curry with tapioca (kappa meen curry), Appam with stew, Puttu and kadala curry (breakfast), Karimeen pollichathu (pearl spot fish in banana leaf, ₹250-400), Kerala prawn curry, Beef fry (popular in Christian areas), Sadya (vegetarian feast on banana leaf for festivals ₹150-250). Best restaurants: Kashi Art Cafe Kochi, Dhe Puttu, Grand Hotel Trivandrum.", "metadata": {"destination": "Kerala", "source": "food_guide", "type": "food"}},
    {"id": "kerala_hidden", "text": "Hidden gems in Kerala: Bekal Fort (Kasaragod, largest fort in Kerala, stunning sea views, very few tourists), Varkala Cliff (natural spring on beach, less crowded than Kovalam), Silent Valley National Park (pristine rainforest, lion-tailed macaques), Athirappilly Falls (largest waterfall in Kerala, filming location for many movies, ₹30 entry), Parambikulam Tiger Reserve (excellent wildlife sightings, forest stay available).", "metadata": {"destination": "Kerala", "source": "hidden_gems", "type": "hidden_gems"}},

    # ===== RAJASTHAN =====
    {"id": "rajasthan_overview", "text": "Rajasthan is India's largest state known for royal palaces, desert landscapes, and vibrant culture. Golden Triangle extension: Jaipur (Pink City, palaces), Jodhpur (Blue City, Mehrangarh Fort), Udaipur (City of Lakes, most romantic city), Jaisalmer (Golden City, desert, camel safaris), Pushkar (holy lake, camel fair in November), Ranthambore (tiger safari). Best season October-March.", "metadata": {"destination": "Rajasthan", "source": "travel_guide", "type": "overview"}},
    {"id": "rajasthan_budget", "text": "Rajasthan 7-day circuit budget: Train Delhi-Jaipur ₹200-600, Jaipur-Jodhpur ₹150-500, Jodhpur-Jaisalmer ₹200-600, Jaisalmer-Udaipur ₹300-800. Budget guesthouse/hostel ₹500-1000/night. Heritage hotel mid-range ₹2000-4000. Camel safari 1 night Jaisalmer ₹2500-4000. Desert camp ₹3000-6000. Food: thali ₹100-200, restaurant ₹200-400. Entry fees (all forts+palaces) ₹1500-2500 total.", "metadata": {"destination": "Rajasthan", "source": "budget_guide", "type": "budget"}},
    {"id": "rajasthan_jaipur", "text": "Jaipur (Pink City) top attractions: Amber Fort (₹100 Indians, elephant ride ₹1100), City Palace (₹200 entry, museum inside), Hawa Mahal (₹50, best at sunrise), Jantar Mantar UNESCO site (₹200), Nahargarh Fort (sunset views, ₹50), Jal Mahal (lake palace, view from road, free). Best shopping: Johari Bazaar (jewelry), Bapu Bazaar (textiles), MI Road. Try Laal Maas (mutton curry) and Dal Baati Churma.", "metadata": {"destination": "Rajasthan", "source": "jaipur_guide", "type": "attractions"}},
    {"id": "rajasthan_hidden", "text": "Hidden gems in Rajasthan: Bundi (step wells, murals, very few tourists, cheaper than Jaipur), Shekhawati region (open-air art gallery of havelis, Mandawa, Nawalgarh), Osian (desert oasis with ancient temples, near Jodhpur), Kumbhalgarh Fort (second longest wall after Great Wall of China, worth day trip from Udaipur), Bishnoi villages near Jodhpur (wildlife conservation community, blackbuck sightings).", "metadata": {"destination": "Rajasthan", "source": "hidden_gems", "type": "hidden_gems"}},

    # ===== COORG =====
    {"id": "coorg_overview", "text": "Coorg (Kodagu) is Karnataka's coffee country at 1525m altitude. Best October-March. Must visit: Raja's Seat viewpoint (sunrise, ₹20), Abbey Falls (₹50), Dubare Elephant Camp (elephant interaction ₹150-800), Nagarhole National Park (safari ₹800-3000), Iruppu Falls, Talacauvery (source of Cauvery river). Drive from Bangalore 5-6 hours (250km), from Mysore 2 hours (120km).", "metadata": {"destination": "Coorg", "source": "travel_guide", "type": "overview"}},
    {"id": "coorg_budget", "text": "Coorg 3-day budget: Bus from Bangalore ₹300-500, from Mysore ₹150. Homestay including meals ₹1500-3000/night (best experience). Budget guesthouse ₹800-1200. Coffee plantation tour free to ₹500. Abbey Falls ₹50. Elephant camp ₹300-800. Nagarhole safari ₹800-1500. Food included in most homestays. Total 3 days: ₹8,000-15,000 from Bangalore.", "metadata": {"destination": "Coorg", "source": "budget_guide", "type": "budget"}},
    {"id": "coorg_hidden", "text": "Hidden gems in Coorg: Mandalpatti Peak (accessible by jeep, ₹1500-2000 jeep hire, above the clouds view, very few visitors), Nishani Motte trek (challenging, guides needed, pristine forest), Thashola (Coorg's Scotland, rolling hills, off the beaten path), Chelavara Falls (near Napoklu, hidden waterfall, local secret), Brahmagiri Wildlife Sanctuary (trekking, diverse birds, fewer visitors than Nagarhole).", "metadata": {"destination": "Coorg", "source": "hidden_gems", "type": "hidden_gems"}},

    # ===== ANDAMAN =====
    {"id": "andaman_overview", "text": "Andaman and Nicobar Islands - India's tropical paradise with crystal clear water. Main island: Port Blair (capital). Top islands: Havelock (Radhanagar Beach rated Asia's best), Neil Island (peaceful, coral reefs), Baratang (limestone caves, mangroves). Activities: snorkeling, scuba diving, sea walking, glass bottom boat. Best season October-May. Fly from major cities or ship from Kolkata/Chennai.", "metadata": {"destination": "Andaman", "source": "travel_guide", "type": "overview"}},
    {"id": "andaman_budget", "text": "Andaman 6-day budget: Flight from Hyderabad ₹8000-15000 return (book 2 months ahead). Inter-island ferry ₹300-600. Budget guesthouse Port Blair ₹800-1500. Havelock beach hut ₹1500-3000. Scuba diving ₹3500-5000 for 2 dives. Snorkeling ₹500-1000. Sea walking ₹3500. Cellular Jail entry ₹30. Light and Sound show ₹100. Food: fish thali ₹150-250. Total 6 days: ₹25,000-40,000.", "metadata": {"destination": "Andaman", "source": "budget_guide", "type": "budget"}},
    {"id": "andaman_hidden", "text": "Hidden gems in Andaman: Diglipur (North Andaman, turtle nesting at Kalipur beach, Saddle Peak trek, very few tourists), Long Island (pristine beaches, basic accommodation, total peace), Jolly Buoy Island (snorkeling, open only Oct-May, day trip from Port Blair), Ross and Smith Islands (twin islands connected by sandbar, walk between them), Baratang limestone caves (stunning formations, ₹150 permit, forest department boat).", "metadata": {"destination": "Andaman", "source": "hidden_gems", "type": "hidden_gems"}},

    # ===== HIMACHAL =====
    {"id": "spiti_overview", "text": "Spiti Valley is a cold desert mountain valley at 3800-4400m in Himachal Pradesh. Known for Buddhist monasteries, dramatic landscapes, star gazing. Key places: Kaza (district HQ), Key Monastery (1000 years old), Kibber village, Chandratal Lake (camping), Pin Valley National Park (snow leopard habitat). Best time June-September only (road closed in winter). Permit needed for some areas.", "metadata": {"destination": "Spiti", "source": "travel_guide", "type": "overview"}},
    {"id": "shimla_overview", "text": "Shimla is Himachal Pradesh capital and most popular hill station at 2200m. Best season March-June and September-November. Top attractions: Mall Road (shopping, cafes), Christ Church, Jakhu Temple (monkeys, 2.5km trek or ropeway ₹250), Kufri (15km, skiing in winter, yak rides ₹200), Naldehra Golf Course. Toy train from Kalka (UNESCO heritage, 5 hours, ₹300-600). Summer peak is very crowded.", "metadata": {"destination": "Shimla", "source": "travel_guide", "type": "overview"}},

    # ===== VARANASI =====
    {"id": "varanasi_overview", "text": "Varanasi (Kashi/Benares) is India's spiritual capital and oldest living city on the banks of Ganges. Must experience: Ganga Aarti at Dashashwamedh Ghat (evening ceremony, free, arrive early for good spot), sunrise boat ride on Ganges (₹200-500/hour), Kashi Vishwanath Temple, Sarnath (where Buddha gave first sermon, 10km away, ₹100 entry), narrow lane walking, silk weaving workshops.", "metadata": {"destination": "Varanasi", "source": "travel_guide", "type": "overview"}},
    {"id": "varanasi_budget", "text": "Varanasi 3-day budget: Train from major cities ₹200-800. Guesthouse near ghats ₹500-1200/night. Mid-range hotel ₹1500-2500. Boat ride ₹200-500. Sarnath entry ₹100. Temple visits mostly free. Food: kachori sabzi breakfast ₹30-50, thali ₹80-150, lassi at Blue Lassi shop ₹80. Silk scarf souvenir ₹200-500. Total 3 days: ₹5,000-10,000.", "metadata": {"destination": "Varanasi", "source": "budget_guide", "type": "budget"}},
    {"id": "varanasi_hidden", "text": "Hidden gems in Varanasi: Assi Ghat (less touristy, morning yoga sessions, authentic chai stalls), Ramnagar Fort (across river, vintage car museum, free entry to fort, ₹150 museum), Chunar Fort (40km, overlooking Ganges, few tourists), Tulsi Manas Temple (modern temple with scenes from Ramcharitmanas on walls), Banaras Hindu University campus (beautiful architecture, free entry, Bharat Kala Bhavan museum ₹20).", "metadata": {"destination": "Varanasi", "source": "hidden_gems", "type": "hidden_gems"}},

    # ===== GENERAL INDIA TRAVEL TIPS =====
    {"id": "india_transport", "text": "India transport guide: Trains - book on IRCTC.co.in, Tatkal quota for last-minute (₹100-300 extra), Sleeper class budget, 3AC comfortable. Buses - government KSRTC/MSRTC reliable, private Volvo comfortable for overnight. Flights - check Skyscanner, IndiGo and SpiceJet cheapest, book 6-8 weeks ahead. Local: Ola/Uber available in all cities, autorickshaws negotiate price, metro in Delhi/Mumbai/Bangalore/Hyderabad/Chennai.", "metadata": {"destination": "India", "source": "transport_guide", "type": "transport"}},
    {"id": "india_budget_tips", "text": "India budget travel tips: Eat at local dhabas and thali restaurants (₹80-200 for full meal). Stay in hostels (Zostel, Gokulam chains ₹400-800 dorm). Travel overnight by train to save accommodation cost. Free attractions: most temples, ghats, markets, public parks. Bargain at markets (start at 50% of asking price). Use local buses instead of tourist buses (10x cheaper). Street food safe if hot and freshly cooked.", "metadata": {"destination": "India", "source": "budget_tips", "type": "budget"}},
    {"id": "india_best_seasons", "text": "Best time to visit Indian destinations: Himalayas (Manali, Spiti, Ladakh): June-September. Rajasthan: October-March (avoid summer heat). Goa: November-February (peak), monsoon June-September (cheap+green). Kerala: September-March, backwaters year-round. Andaman: October-May. Northeast: October-April. General rule: avoid March-June in plains (extreme heat 40-48°C), July-September in mountains (landslides), June-September in Rajasthan (hot+some rain).", "metadata": {"destination": "India", "source": "seasons_guide", "type": "seasons"}},
]

def seed():
    store = get_vector_store()
    for g in GUIDES:
        store.upsert_travel_guide(doc_id=g["id"], text=g["text"], metadata=g["metadata"])
        print(f"  ✅ {g['id']}")
    print(f"\n🌍 Seeded {len(GUIDES)} documents!")

if __name__ == "__main__":
    seed()